#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-logback-core
Version  : 1.2.1
Release  : 1
URL      : https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.jar
Source0  : https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.jar
Source1  : https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.pom
Source2  : https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.2.1/logback-parent-1.2.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1-only
Requires: mvn-logback-core-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-logback-core package.
Group: Data

%description data
data components for the mvn-logback-core package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/ch/qos/logback/logback-core/1.2.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/ch/qos/logback/logback-core/1.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/ch/qos/logback/logback-core/1.2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/ch/qos/logback/logback-core/1.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/ch/qos/logback/logback-parent/1.2.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/ch/qos/logback/logback-parent/1.2.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.jar
/usr/share/java/.m2/repository/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.pom
/usr/share/java/.m2/repository/ch/qos/logback/logback-parent/1.2.1/logback-parent-1.2.1.pom
